# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the devel branch
  push:
    branches: [ devel, master ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    # Disabling shallow clone is recommended for improving relevancy of reporting
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Prepare Sonar scanner
        run: |
          wget -nv https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-linux.zip
          unzip -q sonar-scanner-cli-4.6.0.2311-linux.zip
          echo "${PWD}/sonar-scanner-4.6.0.2311-linux/bin/" >> $GITHUB_PATH
          wget -nv https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip -q build-wrapper-linux-x86.zip          
          echo "${PWD}/build-wrapper-linux-x86" >> $GITHUB_PATH
      
      - name: Install ccache
        uses: hendrikmuhs/ccache-action@v1.0.3
        
      - name: Install CUDA
        run: source scripts/install_cuda_github.sh
        env: 
          CUDA_VER: 10.2.89

      - name: Install dependencies
        run: sudo apt-get install -y scons libfftw3-dev libopenmpi-dev openmpi-bin libhdf5-dev python3-numpy python3-dev libtiff5-dev unzip

      - name: Compile Xmipp
        run: build-wrapper-linux-x86-64 --out-dir bw-outputs ./xmipp noAsk
        env:
          TRAVIS: 1
          BUILD_TESTS: False
          
      - name: SonarCloud Scan
        run: |
          sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=i2pc
          ls -al .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
